### ISSUE TITLE
Login fails with HTTP 400 after server updates

### ISSUE THREAD

**Issue by nickmurison** [marc2016/panasonic-comfort-cloud-client#13]
It looks like Panasonic made some updates to their Comfort Cloud API during a server update overnight. This breaks clients using this library, such as [https://github.com/ugumba/homey-panasonic-comfort-cloud-alt](https://github.com/ugumba/homey-panasonic-comfort-cloud-alt)

Running `npm test` with valid credentials returns an error:

    login

       ServiceError: Request failed with status code 400
       5 |
       6 |     constructor(message: string, code: number, httpCode: number) {
    >  7 |         super(message)
         |         ^
       8 |         Object.setPrototypeOf(this, new.target.prototype);
       9 |         this.name = 'ServiceError'
      10 |         this._code = code

      at new ServiceError (src/model/ServiceError.ts:7:9)
      at ComfortCloudClient.Object.<anonymous>.ComfortCloudClient.handleError (src/ComfortCloudClient.ts:137:11)
      at ComfortCloudClient.<anonymous> (src/ComfortCloudClient.ts:73:12)
      at step (src/ComfortCloudClient.ts:33:23)
      at Object.throw (src/ComfortCloudClient.ts:14:53)
      at rejected (src/ComfortCloudClient.ts:6:65)

Using a proxy, I've discovered that the call is being rejected by CloudFront:

     HTTP/1.1 400 Bad Request
     Server: CloudFront
     Date: Thu, 14 Sep 2023 16:02:18 GMT
     Content-Type: text/html
     Content-Length: 915
     Connection: close
     X-Cache: Error from cloudfront
     Via: 1.1 [redacted].cloudfront.net (CloudFront)
     X-Amz-Cf-Pop: [redacted]
     X-Amz-Cf-Id: [redacted]
     
     <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
     <HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
     <TITLE>ERROR: The request could not be satisfied</TITLE>
     </HEAD><BODY>
     <H1>400 ERROR</H1>
     <H2>The request could not be satisfied.</H2>
     <HR noshade size="1px">
     Bad request.
     We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
     <BR clear="all">
     If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
     <BR clear="all">
     <HR noshade size="1px">
     <PRE>
     Generated by cloudfront (CloudFront)
     Request ID: [redacted]
     </PRE>
     <ADDRESS>
     </ADDRESS>
     </BODY></HTML>

**Comment by nickmurison** [comment]
Looks like you fixed this with https://github.com/marc2016/panasonic-comfort-cloud-client/commit/557f2a9b951a7f8d399beaa3b21ec6803ad2c962 thanks!
